spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:0.6b

#输入请求日志
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG


