spring:
  application:
    name: mcp-stdio-client
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_APIKEY}
    mcp:
      client:
        request-timeout: 60s
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

  mandatory-file-encoding: UTF-8


logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
