spring:
  ai:
#    openai:
#      api-key: ${DASHSCOPE_APIKEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      chat:
#        options:
#          model: qwen-plus
    dash-scope:
      api-key: ${DASHSCOPE_APIKEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v2
      image:
        options:
          model: wanx-v1
      rerank:
        options:
          model: gte-rerank
          #          topN: 5
      workspace-id: ${DASHSCOPE_WORKSPACEID}


    vectorstore:
      redis:
        initialize-schema: true

    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
          request-timeout: 30s

  mandatory-file-encoding: UTF-8



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base_ai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allow
    username: root
    password: 123456

  data:
    redis:
      database: 0
      timeout: 10s
      host: localhost
      port: 6379
      password: 123456
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  neo4j:
    authentication:
      username: neo4j
      password: 12345678
    uri: bolt://localhost:7687

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeHandlersPackage: com.nh.micro.ext.th
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      # 全局逻辑删除配置
      logic-delete-field: isDeleted
      logic-delete-value: true
      logic-not-delete-value: false
#输入请求日志
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

