spring:
  profiles:
    active: qw
    application:
      name: wm-spring-ai

server:
  port: 8001
  servlet:
    context-path: /ai

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wm.ai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn